apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  selector:
    type: NodePort
    selector:
      app: posts-srv
    ports:
      - name: posts
        port: 4000
        targetPort: 4000
        protocol: TCP

